# site settings
title: Greetings to everyone
subtitle: Homepage
email: dikshant1212hsr@gmail.com
description : If you wanna have some, then come and get some
baseurl: "/solid-state-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://Dikshant.github.io" # the base hostname & protocol for your site
author:
street_address: Room No. 160, Hostel 3, IIT Bombay
city: Mumbai
state: Maharashtra
zip_code: 400076
country: India
phone: 9306348233

# social settings
500px_url:
facebook_url: https://www.facebook.com/?ref=tn_tnmn
github_url: https://github.com/Dikshuy
gitlab_url:
googleplus_url: 
instagram_url: https://www.instagram.com/__dikshant_/?hl=en
linkedin_url: https://www.linkedin.com/in/dikshant-shehmar-a95956174/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

menus:
  - Home: "/index.html"
  - Generic: "/generic.html"
  - Elements: "/elements.html"
  - Log in: "#"
  - Sign up: "#"

sass:
  style: compressed
